export const TOKENS = [
    {
        name: "USDC",
        symbol: "USDC",
        color: "text-blue-400",
        bg: "from-blue-500 to-teal-500",
        buttonColor: "bg-blue-600 hover:bg-blue-700",
        cardGlow: "shadow-blue-500/50",
        price: "1.00",
        marketCap: "28.5B",
        imageUrl: "https://cryptologos.cc/logos/usd-coin-usdc-logo.svg?v=034",
    },
    {
        name: "USDT",
        symbol: "USDT",
        color: "text-green-400",
        bg: "from-green-500 to-lime-500",
        buttonColor: "bg-green-600 hover:bg-green-700",
        cardGlow: "shadow-green-500/50",
        price: "1.00",
        marketCap: "90.2B",
        imageUrl: "https://cryptologos.cc/logos/tether-usdt-logo.svg?v=034",
    },
    {
        name: "DAI",
        symbol: "DAI",
        color: "text-yellow-400",
        bg: "from-yellow-500 to-orange-500",
        buttonColor: "bg-yellow-600 hover:bg-yellow-700",
        cardGlow: "shadow-yellow-500/50",
        price: "1.00",
        marketCap: "5.3B",
        imageUrl: "https://cryptologos.cc/logos/multi-collateral-dai-dai-logo.svg?v=034",
    },
];